# Generated by Django 4.1.1 on 2023-07-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='startDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
