# Generated by Django 4.1.1 on 2023-07-10 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeds', '0002_alter_feed_feeduser'),
        ('userprofile', '0002_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commentPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.feed')),
                ('commentUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile')),
            ],
        ),
    ]
